Read both Content-Length header and req.ContentLength
yookoala/gofast pull request #81
Opened 2024-01-29 04:39 UTC by cseufert

This should fix an issue where if you put a fcgi application behind fcgi listener, the content length is lost.

Eg (HTTP req) -> WebServer -> fastcgi -> (Go App with fcgi + http + gofast) -> PHP

All requests lose their body.

2024-01-29 07:04 UTC, yookoala requested changes
Nice addon! Thanks a lot!

One thing needed before accepting the changes. From [documentation](https://pkg.go.dev/net/http#Request),

```go
	// ContentLength records the length of the associated content.
	// The value -1 indicates that the length is unknown.
	// Values >= 0 indicate that the given number of bytes may
	// be read from Body.
	//
	// For client requests, a value of 0 with a non-nil Body is
	// also treated as unknown.
	ContentLength int64
```

But as [RFC9110](https://www.rfc-editor.org/rfc/rfc9110#field.content-length) specified, `Content-Length` should be "a decimal non-negative integer number of octets". So passing the `-1` from Go to fcgi application might cause unexpected behaviour.

I think it's best if the request has no `Content-Length` header and `r.ContentLength` is -1, then we simply omit the header field.

2024-01-29 22:30 UTC, cseufert commented
I have changed the logic, so the content length header is only set when there is an RFC-compliant content length.


PS `gofmt` seems to have decided to reformat a bunch of the comments.... I can fix this manually if it's a problem.

2024-01-30 02:22 UTC, yookoala approved these changes
Thank! No need to change about the gofmt.

P.S. What was the rule / option you used for gofmt?

2024-01-30 02:23 UTC, merged

2024-01-30 02:31 UTC, cseufert commented
@yookoala Not sure, I have been using GoLand and the default is to reformat on save, via gofmt, there does not appear to be specific settings for the formatter. I was using go 1.21, it looks like in go 1.19 there were some updates to the comments formatting.

2024-01-30 02:33 UTC, yookoala commented
@cseufert: I want to incorp your formatting rules to CI, if possible. My gofmt didn't change the comment formatting. Will try with go1.21. Thanks.